apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: ${{values.system | dump}}
  type:  ${{values.type | dump}}
  lifecycle: ${{values.lifecycle | dump}}
  owner: ${{values.owner | dump}}
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{values.env + "-" + values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id | dump}}
    sonarqube.org/project-key: ${{values.component_id | dump}}
    grafana/tag-selector: "Kubernetes"
    prometheus.io/rule: container_cpu_usage_seconds_total{namespace=${{values.component_id | dump}}}
    prometheus.io/alert: all
  tags:
    - golang
    - ${{values.system | dump}}
    - ${{values.type | dump}}
    - ${{values.lifecycle | dump}}
  links:
    - url: https://${{values.component_id}}.${{ values.kubernetes.network.domain }}
      title: Website
      icon: Website
    - url: https://grafana.diegoluisi.eti.br/
      title: Dashboard
      icon: dashboard
    - url: https://alerts.diegoluisi.eti.br/
      title: Alerts
      icon: alert
    - url: https://argocd.diegoluisi.eti.br/applications/${{values.env + "-" + values.component_id}}?resource=
      title: ArgoCD
      icon: cloud
    - url: https://grafana.diegoluisi.eti.br/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=Prometheus&var-namespace=${{values.component_id}}&var-resolution=30s
      title: Logs
      icon: cloud

