apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{values.component_id | dump}}
  links:
    - url: https://${{values.component_id}}.diegoluisi.eti.br
      title: Website
      icon: Website
  tags:
    - golang
    - ${{values.system | dump}}
    - ${{values.type | dump}}
    - ${{values.lifecycle | dump}}
spec:
  system: ${{values.system | dump}}
  type:  ${{values.type | dump}}
  lifecycle: ${{values.lifecycle | dump}}
  owner: ${{values.owner | dump}}
