name: Feature ✨

on:
  push:
    branches:
      - 'feature/**'
    paths-ignore:
      - README.md
      - catalog-info.yaml
      - 'docs/**'


jobs:
  env:
    uses: analect-io/.github/.github/workflows/env.yaml@main

  test:
    uses: analect-io/.github/.github/workflows/test.yaml@main
    needs:
      - env

  quality-gate:
    uses: analect-io/.github/.github/workflows/sonarqube.yaml@main
    secrets: inherit
    needs:
      - env

  code-scan:
    uses: analect-io/.github/.github/workflows/synk-golang.yaml@main
    secrets: inherit
    needs:
      - env

  notify:
    uses: analect-io/.github/.github/workflows/notify.yaml@main
    if: always()
    secrets: inherit
    needs:
      - env
      - test
      - quality-gate
      - code-scan
      # - action-pull-request